spring.application.name: myarmy

---

dashboard.url: http://127.0.0.1

---

spring.jpa:
  database: MYSQL
  showSql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  properties.hibernate.hbm2ddl.auto: update
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true
---

logging.level:
  com.skplanet.rnb: DEBUG
  org.springframework: INFO
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
  org.hibernate.type.BasicTypeRegistry: WARN
---

spring.datasource.url: jdbc:mysql://52.78.173.18/myarmy?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: myarmy
spring.datasource.password: 1234
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.initialize: true

#spring.datasource:
 # platform: h2
 #url: jdbc:h2:mem:myarmy;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
 # username: sa
 # initialize: true
---
spring.h2.console:
  enabled: true
  path : /h2-console
  settings.web-allow-others: true
---

spring.profiles: local-test

---
### jwt Settings ###
jwt.secret: a1g2y47dg3dj59fjhhsd7cnewy73j
jwt.expiration: 6048000
jwt.tokenheader: X-Auth-Token


---
test.token : eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJpd2J0YmdvdHdfQGdtYWlsLmNvbSIsImV4cCI6MTQ5NTYzMjUyMn0.DuYCh-DrwtyNHHGlqaj0j9op9k9tAb8Fg-xXsD2Nc1m0mqkQ0tyuo3yV7OnvCN4sOLoJm4EVUDYOizW-OPmhQA

---
mail:
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  username: win3winkr@gmail.com
  password: dnlsdnls3#
  smtp:
    start-tls-enable: true
    auth: true